import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#fbf9f6",
        "on-background": "#1b1c1a",
        surface: "#fbf9f6",
        "surface-dim": "#dbdad7",
        "surface-bright": "#fbf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f0",
        "surface-container": "#efeeeb",
        "surface-container-high": "#eae8e5",
        "surface-container-highest": "#e4e2df",
        "surface-variant": "#e4e2df",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#424841",
        "inverse-surface": "#30312f",
        "inverse-on-surface": "#f2f0ed",
        outline: "#727970",
        "outline-variant": "#c2c8bf",
        "surface-tint": "#446647",

        primary: "#17381d",
        "primary-container": "#2e4f32",
        "on-primary": "#ffffff",
        "on-primary-container": "#9bc09b",
        "primary-fixed": "#c6edc5",
        "primary-fixed-dim": "#aad0aa",
        "on-primary-fixed": "#012109",
        "on-primary-fixed-variant": "#2d4e31",
        "inverse-primary": "#aad0aa",

        secondary: "#615e58",
        "secondary-container": "#e7e2da",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#67645e",
        "secondary-fixed": "#e7e2da",
        "secondary-fixed-dim": "#cac6bf",
        "on-secondary-fixed": "#1d1b17",
        "on-secondary-fixed-variant": "#494741",

        tertiary: "#4a2a00",
        "tertiary-container": "#693e00",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f5a648",
        "tertiary-fixed": "#ffdcbb",
        "tertiary-fixed-dim": "#ffb869",
        "on-tertiary-fixed": "#2b1700",
        "on-tertiary-fixed-variant": "#673d00",

        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "gutter-mobile": "1rem",
        margin: "2.5rem",
        "margin-mobile": "1.25rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        sans: ["var(--font-plus-jakarta)", "system-ui", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta)", "sans-serif"],
        "display-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "display-lg-mobile": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-sm": ["var(--font-plus-jakarta)", "sans-serif"],
        "label-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "label-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "label-sm": ["var(--font-plus-jakarta)", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
