import {
  Inspection,
  Checkpoint,
  Issue,
  Observation,
  InspectionRule,
  TranscriptMessage,
} from "../types/inspection";

export const initialCheckpoints: Checkpoint[] = [
  {
    id: "chk-1",
    name: "Cold Storage Line #1",
    category: "temperature",
    description: "Main walk-in chillers and prep reach-in units (Target 0–4°C, Max 5°C)",
    status: "warning",
    target: "0–4°C",
    currentValue: "6°C",
    unit: "°C",
    notes: "Requires attention: voice correction re-evaluated to 6°C, exceeding 5°C threshold",
    updatedAt: "10:41 AM",
  },
  {
    id: "chk-2",
    name: "Walk-in Deep Freezer",
    category: "temperature",
    description: "Bulk protein preservation vault and gelato hold",
    status: "verified",
    target: "< -18°C",
    currentValue: "-18°C",
    unit: "°C",
    notes: "Within compliant range",
    updatedAt: "10:42 AM",
  },
  {
    id: "chk-3",
    name: "Food Separation & Storage",
    category: "storage",
    description: "Raw poultry and animal proteins isolated below ready-to-eat produce",
    status: "warning",
    target: "Zero cross-contamination",
    currentValue: "Flagged",
    notes: "Raw poultry detected stored above prep greens in Walk-in Rack B",
    updatedAt: "10:43 AM",
  },
  {
    id: "chk-4",
    name: "Hand Washing Station #1 & #2",
    category: "hygiene",
    description: "Antibacterial soap, warm flow (38–43°C), disposable towels",
    status: "pending",
    target: "100% Stocked",
    notes: "Awaiting paper towel restock verification",
    updatedAt: "10:44 AM",
  },
  {
    id: "chk-5",
    name: "Prep Table Surfaces",
    category: "cleaning",
    description: "Sanitized 304 food-grade stainless steel surfaces",
    status: "verified",
    target: "Sanitized",
    currentValue: "Cleared",
    notes: "Pass line cleared and wiped with approved sanitizing wipe",
    updatedAt: "10:44 AM",
  },
  {
    id: "chk-6",
    name: "Sanitizer Buckets (Pass & Butchery)",
    category: "cleaning",
    description: "Quaternary ammonium concentration verification (200–400 PPM)",
    status: "verified",
    target: "200 PPM",
    currentValue: "200 PPM",
    notes: "Titration strip verified at optimal level",
    updatedAt: "10:45 AM",
  },
  {
    id: "chk-7",
    name: "Expiration Labels & FIFO",
    category: "labels",
    description: "First-in, first-out rotation tags across prep pans with discard dates",
    status: "pending",
    target: "All dates valid",
    notes: "Prep crew rotation sweep underway",
    updatedAt: "10:45 AM",
  },
  {
    id: "chk-8",
    name: "Waste Receptacles & Grease Interceptor",
    category: "waste",
    description: "Foot-pedal cans relined, lids tight, interceptor cleaned",
    status: "pending",
    target: "Emptied & relined",
    notes: "Closing sweep scheduled",
    updatedAt: "10:46 AM",
  },
];

export const initialIssues: Issue[] = [
  {
    id: "iss-1",
    category: "Food Separation",
    title: "Food separation violation",
    severity: "high",
    description:
      "Raw poultry stored above prep greens in Walk-in Refrigerator #2. Immediate cross-contamination risk identified during line walkthrough.",
    status: "open",
    location: "Main Walk-in Rack B",
    createdAt: "13:14",
    loggedBy: "Arun",
    observedText: "Raw chicken is stored below unsealed vegetables.",
    flagReason:
      "KitchenGuard detected a food-separation issue based on the configured inspection rule.",
    recommendedAction: "Separate raw and ready-to-eat food immediately.",
    history: [
      { time: "10:42", action: "Observation recorded via voice" },
      { time: "10:43", action: "Rule triggered: Critical cross-contamination limit" },
      { time: "10:45", action: "Assigned to station chef for physical separation" },
    ],
  },
  {
    id: "iss-2",
    category: "Hand Washing",
    title: "Hand-wash station paper towels missing",
    severity: "medium",
    description:
      "Station #3 dispenser empty during 13:10 check. Backup stock present in dry chemical locker.",
    status: "open",
    location: "Pastry & Saucier Pass",
    createdAt: "13:10",
    loggedBy: "Arun",
    observedText: "The paper towels are missing.",
    flagReason:
      "Hand washing station missing mandatory single-use drying towels per health sanitation standard.",
    recommendedAction: "Restock dispenser from chemical supply storage locker.",
    history: [
      { time: "13:10", action: "Voice report: dispenser depleted" },
      { time: "13:11", action: "Rule triggered: Hand-wash compliance check" },
    ],
  },
  {
    id: "iss-3",
    category: "Cold Storage",
    title: "Cold storage door seal & temperature calibration",
    severity: "high",
    description:
      "Temperature re-verified at 3.8°C following gasket adjustment on Reach-in Unit C. Stabilized within safe range.",
    status: "resolved",
    location: "Reach-in Unit C",
    createdAt: "11:20",
    resolvedAt: "11:42",
    loggedBy: "Marcus K.",
    observedText: "Walk-in refrigerator is six degrees... adjusted damper, re-checked temp at 3.8 degrees",
    flagReason: "Exceeded 5.0°C upper limit before damper adjustment.",
    recommendedAction: "Adjust seal gasket and monitor recovery cycle.",
    history: [
      { time: "11:20", action: "Logged at 6°C" },
      { time: "11:25", action: "Damper realigned and gasket sanitized" },
      { time: "11:42", action: "Re-verified at 3.8°C. Marked resolved." },
    ],
  },
];

export const initialRules: InspectionRule[] = [
  {
    id: "rule-1",
    category: "Temperature",
    name: "Cold storage temperature",
    targetThreshold: "≤ 5.0°C",
    action: "Flag when above threshold (critical limit 5°C)",
    description:
      "Monitors walk-in chillers and prep reach-ins. Requires immediate chef sign-off or corrective re-chill if exceeded.",
    enabled: true,
    severity: "high",
    standard: "HACCP CCP-1",
  },
  {
    id: "rule-2",
    category: "Temperature",
    name: "Freezer deep preservation threshold",
    targetThreshold: "≤ -18.0°C",
    action: "Alert when temperatures rise above -15.0°C",
    description:
      "Bulk meat and seafood preservation freezer control point to prevent ice recrystallization.",
    enabled: true,
    severity: "high",
    standard: "HACCP CCP-1B",
  },
  {
    id: "rule-3",
    category: "Storage",
    name: "Food separation & storage vertical stacking",
    targetThreshold: "Poultry below produce",
    action: "Immediate stop-line warning for cross-contamination",
    description:
      "Raw poultry must always be stored on the lowest racks below washed salad greens and ready-to-eat foods.",
    enabled: true,
    severity: "critical",
    standard: "FDA Food Code 3-302.11",
  },
  {
    id: "rule-4",
    category: "Hygiene",
    name: "Hand-washing supplies verification",
    targetThreshold: "Soap & Towels confirmed",
    action: "Flag when dispensers empty or water below 38°C",
    description:
      "All dedicated hand-wash sinks must maintain continuous hot water, antibacterial soap, and single-use towels.",
    enabled: true,
    severity: "medium",
    standard: "Culinary Sanitation Directive",
  },
  {
    id: "rule-5",
    category: "Cleaning",
    name: "Surface sanitizer chemical titration",
    targetThreshold: "200–400 PPM",
    action: "Flag if Quat solution drops below 150 PPM",
    description:
      "Requires line sanitizer buckets to be refreshed every 2 hours or when food debris is observed.",
    enabled: true,
    severity: "high",
    standard: "HACCP CCP-3",
  },
  {
    id: "rule-6",
    category: "Labels",
    name: "FIFO rotation & labeling compliance",
    targetThreshold: "7-Day Shelf Life Limit",
    action: "Flag unlabelled containers or dates beyond threshold",
    description:
      "All prep containers must carry standard KitchenGuard labels with preparation date and initialed inspector tag.",
    enabled: true,
    severity: "medium",
    standard: "Operational Standard OS-4",
  },
];

export const sampleObservations: Observation[] = [
  {
    id: "obs-1",
    checkpointId: "chk-1",
    item: "Walk-in refrigerator temperature",
    value: "6°C",
    previousValue: "4°C",
    unit: "°C",
    status: "attention",
    source: "voice",
    timestamp: "08:14:31",
    reason: "Voice correction accepted",
    rawSpokenText: "Actually, the refrigerator was six degrees, not four.",
    understoodEntity: "Walk-in Refrigerator #1 · Temperature: 6°C",
    ruleEvaluation: "Configured limit: ≤ 5°C. Requires attention.",
  },
  {
    id: "obs-2",
    checkpointId: "chk-2",
    item: "Walk-in freezer temperature",
    value: "-18°C",
    unit: "°C",
    status: "verified",
    source: "voice",
    timestamp: "08:14:18",
    rawSpokenText: "Minus eighteen.",
    understoodEntity: "Walk-in Deep Freezer · Temperature: -18°C",
    ruleEvaluation: "Configured limit: ≤ -18°C. Compliant.",
  },
];

export const sampleTranscripts: TranscriptMessage[] = [
  {
    id: "msg-1",
    speaker: "worker",
    speakerName: "Arun",
    role: "Kitchen Supervisor",
    text: "Walk-in refrigerator is four degrees.",
    timestamp: "08:14:02",
  },
  {
    id: "msg-2",
    speaker: "assistant",
    speakerName: "KitchenGuard",
    role: "Voice Agent",
    text: "Recorded 4°C. What is the freezer temperature?",
    timestamp: "08:14:04",
  },
  {
    id: "msg-3",
    speaker: "worker",
    speakerName: "Arun",
    role: "Kitchen Supervisor",
    text: "Minus eighteen.",
    timestamp: "08:14:18",
  },
  {
    id: "msg-4",
    speaker: "assistant",
    speakerName: "KitchenGuard",
    role: "Voice Agent",
    text: "Freezer temperature recorded at −18°C.",
    timestamp: "08:14:20",
  },
  {
    id: "msg-5",
    speaker: "worker",
    speakerName: "Arun",
    role: "Kitchen Supervisor",
    text: "The vegetables are stored above the chicken.",
    timestamp: "08:14:24",
  },
  {
    id: "msg-6",
    speaker: "assistant",
    speakerName: "KitchenGuard",
    role: "Voice Agent",
    text: "Are the vegetables sealed?",
    timestamp: "08:14:26",
  },
  {
    id: "msg-7",
    speaker: "worker",
    speakerName: "Arun",
    role: "Kitchen Supervisor",
    text: "No.",
    timestamp: "08:14:28",
    badge: "Food Separation Alert",
  },
  {
    id: "msg-8",
    speaker: "worker",
    speakerName: "Arun",
    role: "Kitchen Supervisor",
    text: "Actually, the refrigerator was six degrees, not four.",
    timestamp: "08:14:31",
    isCorrection: true,
  },
  {
    id: "msg-9",
    speaker: "assistant",
    speakerName: "KitchenGuard",
    role: "Voice Agent",
    text: "I previously recorded 4°C. Should I replace it with 6°C?",
    timestamp: "08:14:33",
  },
  {
    id: "msg-10",
    speaker: "worker",
    speakerName: "Arun",
    role: "Kitchen Supervisor",
    text: "Yes.",
    timestamp: "08:14:35",
  },
  {
    id: "msg-11",
    speaker: "assistant",
    speakerName: "KitchenGuard",
    role: "Voice Agent",
    text: "Updated Walk-in refrigerator to 6°C. Note: Exceeds 5°C safety limit. Requires attention.",
    timestamp: "08:14:37",
    badge: "Limit Exceeded",
  },
  {
    id: "msg-12",
    speaker: "worker",
    speakerName: "Arun",
    role: "Kitchen Supervisor",
    text: "The paper towels are missing.",
    timestamp: "08:14:45",
  },
  {
    id: "msg-13",
    speaker: "assistant",
    speakerName: "KitchenGuard",
    role: "Voice Agent",
    text: "Flagged Hand-wash Station #3: Paper towels missing. Rule: Sanitary towels required.",
    timestamp: "08:14:47",
    badge: "Issue Flagged",
  },
  {
    id: "msg-14",
    speaker: "worker",
    speakerName: "Arun",
    role: "Kitchen Supervisor",
    text: "Paper towels have been restocked.",
    timestamp: "08:15:10",
  },
  {
    id: "msg-15",
    speaker: "assistant",
    speakerName: "KitchenGuard",
    role: "Voice Agent",
    text: "Hand-wash Station #3 paper towel issue marked resolved.",
    timestamp: "08:15:12",
    badge: "Resolved",
  },
];

export const sampleInspectionRecord: Inspection = {
  id: "KG-2026-0928-0042",
  type: "opening",
  typeName: "Opening Inspection",
  kitchen: "Main Kitchen",
  status: "completed",
  inspector: "Arun Patel",
  inspectorRole: "Kitchen Manager",
  startedAt: "2026-09-28T08:30:00Z",
  completedAt: "2026-09-28T08:42:00Z",
  durationMinutes: 12,
  readinessScore: 87,
  checkpointsTotal: 8,
  checkpointsCompleted: 8,
  issuesCount: 2,
  issuesResolved: 2,
  correctionsCount: 1,
  checkpoints: initialCheckpoints,
  observations: sampleObservations,
  issues: initialIssues,
  corrections: [
    {
      id: "corr-1",
      checkpointId: "chk-1",
      itemName: "Walk-in Refrigerator #1",
      previousValue: "4°C",
      newValue: "6°C",
      reason: "Voice correction by inspector",
      timestamp: "08:14:31",
      status: "accepted",
    },
  ],
  events: [
    {
      id: "evt-1",
      type: "start",
      timestamp: "08:30:00",
      description: "Inspection initiated for Main Kitchen Opening Protocol",
    },
    {
      id: "evt-2",
      type: "observation",
      timestamp: "08:32:15",
      description: "Walk-in Refrigerator parsed at 4°C",
    },
    {
      id: "evt-3",
      type: "correction",
      timestamp: "08:34:02",
      description: "Inspector corrected refrigerator temperature to 6°C",
    },
    {
      id: "evt-4",
      type: "rule_flag",
      timestamp: "08:34:05",
      description: "Threshold alert: 6°C exceeds configured 5°C safety limit",
    },
    {
      id: "evt-5",
      type: "complete",
      timestamp: "08:42:00",
      description: "All 8 checkpoints verified and signed off",
    },
  ],
  transcripts: sampleTranscripts,
};

export const sampleInspectionHistory: Inspection[] = [
  sampleInspectionRecord,
  {
    id: "KG-2026-0928-0041",
    type: "closing",
    typeName: "Cold Storage Audit",
    kitchen: "Main Kitchen",
    status: "completed",
    inspector: "Arun Patel",
    inspectorRole: "Kitchen Manager",
    startedAt: "2026-09-28T11:20:00Z",
    completedAt: "2026-09-28T11:35:00Z",
    durationMinutes: 15,
    readinessScore: 94,
    checkpointsTotal: 6,
    checkpointsCompleted: 6,
    issuesCount: 1,
    issuesResolved: 1,
    correctionsCount: 0,
    checkpoints: initialCheckpoints.slice(0, 6),
    observations: sampleObservations,
    issues: [initialIssues[2]],
    corrections: [],
    events: [],
    transcripts: [],
  },
  {
    id: "KG-2026-0928-0040",
    type: "custom-voice",
    typeName: "Kitchen Walkthrough",
    kitchen: "Main Kitchen",
    status: "needs_review",
    inspector: "Arun Patel",
    inspectorRole: "Kitchen Manager",
    startedAt: "2026-09-28T13:10:00Z",
    durationMinutes: 8,
    readinessScore: 78,
    checkpointsTotal: 8,
    checkpointsCompleted: 6,
    issuesCount: 2,
    issuesResolved: 0,
    correctionsCount: 1,
    checkpoints: initialCheckpoints,
    issues: [initialIssues[0], initialIssues[1]],
    observations: sampleObservations,
    corrections: [],
    events: [],
    transcripts: [],
  },
  {
    id: "KG-2026-0927-0039",
    type: "closing",
    typeName: "Closing Inspection",
    kitchen: "Main Kitchen",
    status: "completed",
    inspector: "Marcus K.",
    inspectorRole: "Sous Chef",
    startedAt: "2026-09-27T22:30:00Z",
    completedAt: "2026-09-27T22:45:00Z",
    durationMinutes: 15,
    readinessScore: 100,
    checkpointsTotal: 12,
    checkpointsCompleted: 12,
    issuesCount: 0,
    issuesResolved: 0,
    correctionsCount: 0,
    checkpoints: initialCheckpoints,
    issues: [],
    observations: [],
    corrections: [],
    events: [],
    transcripts: [],
  },
  {
    id: "KG-2026-0926-0038",
    type: "deep-clean",
    typeName: "Deep Clean Protocol",
    kitchen: "Main Kitchen & Pastry",
    status: "completed",
    inspector: "Elena Rostova",
    inspectorRole: "Sanitation Lead",
    startedAt: "2026-09-26T15:00:00Z",
    completedAt: "2026-09-26T15:35:00Z",
    durationMinutes: 35,
    readinessScore: 92,
    checkpointsTotal: 16,
    checkpointsCompleted: 16,
    issuesCount: 1,
    issuesResolved: 1,
    correctionsCount: 0,
    checkpoints: initialCheckpoints,
    issues: [],
    observations: [],
    corrections: [],
    events: [],
    transcripts: [],
  },
];
